# Generated by Django 4.0.1 on 2022-02-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_completed_order_delivered_and_more'),
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrier',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.Order'),
        ),
    ]
