# Generated by Django 4.0.1 on 2022-02-16 17:32

import carriers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_options_remove_carrier_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='address_proof_document',
            field=models.ImageField(blank=True, help_text='Address proof document', null=True, upload_to=carriers.models.upload_address_proof_document_path, verbose_name='address proof document'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='id_proof_document',
            field=models.ImageField(blank=True, help_text='Id proof document', null=True, upload_to=carriers.models.upload_id_proof_document_path, verbose_name='id proof document'),
        ),
    ]
