# Generated by Django 3.2.9 on 2021-12-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery_addresses',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
