# Generated by Django 3.2.9 on 2022-01-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Product available or not', verbose_name='Is product available'),
        ),
    ]
