# Generated by Django 4.0.1 on 2022-02-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_received_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received_at',
            new_name='delivered_at',
        ),
    ]
