# Generated by Django 4.0.1 on 2022-02-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_options_remove_carrier_orders'),
        ('orders', '0008_rename_completed_order_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='carriers.carrier'),
        ),
    ]
